name: CI-CD-DEMO Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    # SonarCloud Scan
    - name: Run SonarCloud Scan
      uses: SonarSource/sonarqube-scan-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: https://sonarcloud.io

    # secret scanning
  #  - name: Run GitLeaks Secret Scan
   #   uses: gitleaks/gitleaks-action@v2

    - name: Build Docker image
      run: docker build -t cicd-rnd .

    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: cicd-rnd
        format: table
        severity: HIGH CRITICAL
        exit-code: 1
        ignore-unfixed: true
        vuln-type: os,library
          
          
          
  

